/**
 * Responsibility: Provide the built-in scan profile catalog.
 * Must not: Validate profiles, apply overlays, execute scans, or mutate the catalog at runtime.
 * Contract: Provides the initial profiles defined by docs/specs/repository-scan.md.
 */
import type { ScanProfile } from "./scan-profile.js";

export const DOCUMENTATION_CONFLICTS_PROFILE: ScanProfile = {
  id: "documentation-conflicts",
  version: 1,
  name: "Documentation conflicts",
  description: "Map repository documentation with emphasis on conflicting authority, stale claims, and missing ownership.",
  instructions: [
    "Read repository rules and establish the documented SSOT order before interpreting claims.",
    "Use the run coverage derived from the selected completed repository index as the bounded source inventory for this scan.",
    "Map bounded concepts and their owning source sections before creating findings.",
    "Represent every conflict with exact source claims, anchors, revisions, and the expected owner.",
    "Distinguish product direction, current contract, implementation evidence, and historical material.",
  ],
  scope: {
    include: ["AGENTS.md", "README.md", "docs/**/*.md", "**/README.md"],
    exclude: ["node_modules/**", "dist/**", "vendor/**", "docs/archive/**"],
  },
  sourceTypes: ["project-rules", "specification", "architecture", "product-direction", "operational-documentation"],
  criteria: [
    { id: "contradictory-claims", description: "Two current sources make incompatible claims about the same concern." },
    { id: "duplicate-authority", description: "Multiple sources present themselves as owner of the same contract." },
    { id: "stale-documentation", description: "A current-looking source describes superseded behavior or structure." },
    { id: "broken-references", description: "A referenced document, section, symbol, or link does not exist." },
    { id: "missing-owner", description: "A material concern has no explicit owning source." },
    { id: "ambiguous-status", description: "Direction, implementation, history, or deprecation status is unclear." },
    { id: "direction-as-implementation", description: "Future direction is presented as implemented behavior." },
  ],
  duplicateAuthorityClaimPatterns: [
    "\\b(single source of truth|source of truth|canonical|authoritative)\\b.*\\b(?:lives here|belongs here|defined here|recorded here|maintained here)\\b",
    "\\bthis\\s+(?:document|doc|page|file|guide|spec|readme|runbook|playbook|section)\\b.*\\b(single source of truth|source of truth|canonical|authoritative)\\b",
    "\\b(?:document|doc|page|file|guide|spec|readme|runbook|playbook|section)\\b.*\\b(?:is|are|remains)\\s+(?:the\\s+)?(single source of truth|source of truth|canonical|authoritative)\\b",
    "\\b(?:document|doc|guide|spec|readme|runbook|playbook|page|file)\\b.*\\bowned by\\b",
  ],
  duplicateAuthorityIgnoredTopicTokens: [
    "a",
    "an",
    "and",
    "are",
    "as",
    "authoritative",
    "be",
    "by",
    "canonical",
    "doc",
    "file",
    "for",
    "here",
    "is",
    "it",
    "lives",
    "of",
    "on",
    "page",
    "source",
    "the",
    "this",
    "truth",
  ],
  duplicateAuthorityGenericTopicTokens: [
    "agent",
    "agents",
    "architecture",
    "design",
    "doc",
    "guide",
    "module",
    "owner",
    "ownership",
    "policy",
    "project",
    "projection",
    "repo",
    "repository",
    "rule",
    "runtime",
    "scan",
    "spec",
    "system",
    "tool",
    "workflow",
    "workspace",
  ],
  missingOwnerMaterialPaths: ["readme.md"],
  missingOwnerMaterialFileNames: ["agents.md"],
  missingOwnerIgnoredPathMarkers: [
    "glossary",
    "changelog",
    "release-notes",
    "terms",
    "archive",
    "history",
    "docs/ai/",
    "docs/adr/",
    "docs/design/",
    "docs/product/",
  ],
  missingOwnerPathKeywords: ["contract", "policy", "runbook", "playbook", "operations", "ownership", "responsibility", "schema", "api", "mcp"],
  missingOwnerTextKeywords: ["rollback", "incident", "operator", "on-call", "oncall"],
  staleDocumentationMaterialFileNames: ["agents.md", "readme.md"],
  staleDocumentationIgnoredPathMarkers: ["glossary", "changelog", "release-notes", "terms", "archive", "history"],
  staleDocumentationPathKeywords: [
    "architecture",
    "design",
    "spec",
    "contract",
    "policy",
    "workflow",
    "runbook",
    "playbook",
    "guide",
    "deploy",
    "operations",
    "runtime",
    "storage",
    "transport",
  ],
  staleDocumentationTextKeywords: ["primary", "default", "supported", "deprecated", "removed", "deferred", "runtime", "backend", "interface", "target"],
  staleDocumentationNonCurrentPathMarkers: ["legacy", "deprecated", "archive", "histor", "changelog", "release-notes"],
  staleDocumentationNonCurrentTextMarkers: [
    "legacy documentation",
    "legacy doc",
    "historical reference",
    "for historical reference",
    "archived document",
    "archived for reference",
    "superseded by",
    "this document is obsolete",
    "this document is deprecated",
  ],
  ssotOrder: ["AGENTS.md", "docs/specs/**", "docs/architecture*", "docs/product/**", "implementation"],
  requiredOutputs: ["document-inventory", "concept-map", "findings", "coverage-report"],
};

export const CODE_QUALITY_PROFILE: ScanProfile = {
  id: "code-quality-review",
  version: 1,
  name: "Code quality review",
  description: "Map implementation boundaries and record code, contract, test, and runtime problems.",
  overlayStem: "code-quality",
  instructions: [
    "Read repository rules, architecture, and relevant contracts before assessing implementation.",
    "Use the run coverage derived from the selected completed repository index as the bounded code and test inventory for this scan.",
    "Map components and boundaries before recording local symptoms.",
    "Attach code symbols, tests, and contract sources to every finding.",
    "Use technical finding kinds such as architecture-risk, runtime-risk, authority-gap, test-gap, and deployment-risk when they describe the problem more precisely than documentation-oriented kinds.",
    "Separate verified defects from risks and missing evidence.",
  ],
  scope: {
    include: ["src/**", "apps/**", "packages/**", "tests/**", "docs/specs/**"],
    exclude: ["node_modules/**", "dist/**", "coverage/**", "vendor/**"],
  },
  sourceTypes: ["project-rules", "specification", "code", "test", "runtime-evidence"],
  criteria: [
    { id: "contract-drift", description: "Implementation behavior differs from the owning contract." },
    { id: "missing-tests", description: "A material boundary or failure mode lacks verification." },
    { id: "duplicate-responsibility", description: "Multiple modules own the same responsibility." },
    { id: "boundary-violation", description: "A module performs work owned by another boundary." },
    { id: "unsafe-failure", description: "Invalid state or IO failure is hidden or ambiguously recovered." },
    { id: "concurrency-risk", description: "Async or concurrent behavior has an unbounded or unverified race." },
    { id: "undocumented-api", description: "A public API or tool behavior lacks an owning contract." },
  ],
  duplicateResponsibilityTopLevelSymbolKinds: ["class", "interface", "enum", "record", "function"],
  duplicateResponsibilityIgnorePathGlobs: [
    "**/archive/**",
    "**/archives/**",
    "**/archived/**",
    "**/legacy/**",
    "**/deprecated/**",
    "**/generated/**",
    "**/__generated__/**",
    "**/*.generated.*",
    "**/fixtures/**",
    "**/__fixtures__/**",
    "**/examples/**",
    "**/example/**",
    "**/samples/**",
    "**/sample/**",
    "**/demo/**",
    "**/demos/**",
    "**/mocks/**",
    "**/__mocks__/**",
    "**/*.mock.*",
    "**/*.stories.*",
    "**/storybook/**",
  ],
  ssotOrder: ["AGENTS.md", "docs/specs/**", "docs/architecture*", "implementation", "tests"],
  requiredOutputs: ["document-inventory", "concept-map", "findings", "coverage-report"],
};

export const INITIAL_SCAN_PROFILES: ScanProfile[] = [DOCUMENTATION_CONFLICTS_PROFILE, CODE_QUALITY_PROFILE];
